ps1/config/routes.rb
Rails.application.routes.draw do
  root 'problem_sets#index'
  get 'problem_sets/index'
  get 'youtube_trends/index'
  get 'youtube_trends', to: 'youtube_trends#index'
  get 'divide-by-zero', to: 'youtube_trends#divide_by_zero'
  get 'about-to-divide-by-zero', to: 'youtube_trends#about_to_divide_by_zero'
  get 'ps-1', to: 'youtube_trends#ps1'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ps1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ps1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

ps1/app/controllers/problem_sets_controller.rb
# TODO
class ProblemSetsController < ApplicationController
  def index
  end
end

ps1/app/controllers/youtube_trends_controller.rb
# TODO
class YoutubeTrendsController < ApplicationController
  def index
    @top_ten_youtube = top_ten_youtube
  end

  def youtube_trending
    Nokogiri::HTML(open('https://www.youtube.com/feed/trending'), nil, 'UTF-8')
  end

  def thumbnail_urls
    img_elements = youtube_trending.css('.expanded-shelf-content-item-wrapper .yt-thumb span img').to_s
    URI.extract(img_elements).delete_if do |url|
      url.include? '.gif'
    end
  end

  def titles
    youtube_trending.css('a.yt-uix-tile-link').map { |title| title['title'] }
  end

  def video_urls
    youtube_trending.css('a.yt-uix-tile-link').map { |url| 'https://www.youtube.com' + url['href'] }
  end

  def top_ten_youtube
    titles.zip(thumbnail_urls, video_urls).first(10)
  end

  def divide_by_zero
    logger.error 'About to divide by zero'
    1 / 0
  end
end

ps1/app/helpers/application_helper.rb
module ApplicationHelper
end

ps1/app/helpers/problem_sets_helper.rb
# No implementation here yet.
module ProblemSetsHelper
end

ps1/app/helpers/youtube_trends_helper.rb
# No implementation here yet.
module YoutubeTrendsHelper
end

ps1/app/views/layouts/_footer.html.erb
<p>
  <a href="http://validator.w3.org/check?uri=referer"><img
  src="http://www.w3.org/Icons/valid-xhtml10"
  alt="Valid XHTML 1.0!" height="31" width="88" /></a>
</p>

ps1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="th">
  <head>
    <title>Web6 Projects</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body  style="color:#333; font-family: Verdana, Arial, Helvetica, sans-serif; padding:40px">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

ps1/app/views/problem_sets/index.html.erb
<h2>Problem Set 1</h2>
<br>
<div style="font-size: 18px; padding-bottom: 15px">The details of this project are available <a href="/ps1/report/ps1.pdf">here</a>.</div>
<div class="pgLinks">1.<%= link_to "Youtube Top Trends", youtube_trends_path %></div>
<div class="pgLinks">2. <%= link_to "About to divide by zero", about_to_divide_by_zero_path %></div>

ps1/app/views/youtube_trends/about_to_divide_by_zero.html.erb
<div style="font-size: 18px; padding-bottom: 15px">The details about this task are available <a href="/ps1/report/ps1_divide_by_zero.pdf">here</a>.</div>

<%= link_to 'Divide by zero', divide_by_zero_path %>

ps1/app/views/youtube_trends/index.html.erb
<div id="pgTitle" style="text-align: center; padding-bottom: 20px"><h2>Top Ten Trending Videos On <span style="color:#cc181e">YouTube</span></h2></div>

<div id="pgContent">
  <ol>
    <% @top_ten_youtube.each do |video| %>
    <li style="padding-bottom: 15px">
      <%= video[0] %>
      <a href="<%= video[2] %>" title="<%= video[0] %>"><br>
        <img src="<%= video[1] %>" alt="<%= video[0] %>" width="300">
      </a>
    </li>
    <% end %>
  </ol>
</div>

ps1/app/views/youtube_trends/ps1.html.erb
<h2>Problem Set 1</h2>
<br>
<div style="font-size: 18px; padding-bottom: 15px">The details of this project are available <a href="/ps1/report/ps1.pdf">here</a>.</div>
<div class="pgLinks">1.<%= link_to "Youtube Top Trends", youtube_trends_path %></div>
<div class="pgLinks">2. <%= link_to "About to divide by zero", '/about-to-divide-by-zero' %></div>